### ISSUE TITLE
Incompatible with panel v1.0

### ISSUE THREAD

**Issue by INfoUpgraders** [iamkubi/pydactyl#17]
pydactyl is incompatible with panel version 1.0 (latest version)

**Comment by fadedmax** [comment]
have you even read the readme, and give more detail?
\

**Comment by nullstalgia** [comment]
Update for this: V1.0 is now out and stable.

Some actions do seem to work (stopping and starting), but getting status does not seem to work. I haven't done a deep dive into the errors, just a surface-level peak based on a Discord.py + Py-Dactyl bot I have

**Comment by nullstalgia** [comment]
API Reference for @iamkubi 

https://dashflo.net/docs/api/pterodactyl/v1/

From the Pterodactyl Discord Server:

![image](https://user-images.githubusercontent.com/20761757/95694599-c7a8a000-0be7-11eb-855e-12a3fda551de.png)

**Comment by iamkubi** [comment]
Yep, I'm quite familiar with the API changes and that much of the client API doesn't work anymore.  Unfortunately I'm pretty busy at the moment, so it will probably be a week or two before I can get an update out.

**Comment by nullstalgia** [comment]
Understandable

If you need some simple testing I can oblige, but as I said, I have simple needs. :)

**Comment by INfoUpgraders** [comment]
Nice to see the v1 api reference is finished

**Comment by nullstalgia** [comment]
Any chance of an update coming soon? :)

**Comment by iamkubi** [comment]
Yes, I hope to have a chance this week to update it.

**Comment by vejskvit** [comment]
Still nothing looks like I'm going to have to write my own.

**Comment by INfoUpgraders** [comment]
Yep. I'll be making one soon and publishing it on GitHub.
