### ISSUE TITLE
Checking for server response

### ISSUE THREAD

**Issue by DiSay1** [iamkubi/pydactyl#21]
Please add the function to check the response of the server, i.e. when you enter the command into the server console to write the response of the server.

**Comment by iamkubi** [comment]
Not possible.  In 1.0 you can connect and read the console, which will be implemented sometime sooner or later, but as far as I know Pterodactyl doesn't provide any way to get the console output for a successful console command.  pydactyl already includes any response that comes from the API.

If it does exist and you can point me to an example of how to do this with the API feel free to reply and it can be added.
