### ISSUE TITLE
Update to v1.0

### ISSUE THREAD

**Issue by RedstonedLife** [iamkubi/pydactyl#22]
Many of the features the API of Pterodactyl offers are not available.
For example. You can post/get files, list directories, and yet the feature is not available.

**Comment by iamkubi** [comment]
I'm about half done implementing the new files endpoints.  Should have something ready within a day or two.

**Comment by Okupateco** [comment]
> I'm about half done implementing the new files endpoints. Should have something ready within a day or two.

Would you go ahead and create a separate branch?  I'd like to make some commits.

**Comment by iamkubi** [comment]
> > I'm about half done implementing the new files endpoints. Should have something ready within a day or two.
> 
> Would you go ahead and create a separate branch? I'd like to make some commits.

You can feel free to send PRs, but that doesn't require another branch.  I don't have any plans to continue to develop for 0.7 so 1.x changes go in the master branch.

**Comment by Okupateco** [comment]
> > > I'm about half done implementing the new files endpoints. Should have something ready within a day or two.
> > 
> > 
> > Would you go ahead and create a separate branch? I'd like to make some commits.
> 
> You can feel free to send PRs, but that doesn't require another branch. I don't have any plans to continue to develop for 0.7 so 1.x changes go in the master branch.

Could you push your commits, current code is still outdated.

**Comment by danielrosnl** [comment]
For everyone who are still wanting a Pterodactyl v1 Python API, I made a repository called PteroPython

**Comment by iamkubi** [comment]
All API endpoints should be implemented as of v1.1.0.
