### ISSUE TITLE
Listing Servers Issue

### ISSUE THREAD

**Issue by Jaxon0** [iamkubi/pydactyl#34]
hey there,
```client.client.list_servers()``` seems to be broken/not working.

**Comment by ens-gijs** [comment]
try `client.servers.list_servers()` instead

**Comment by iamkubi** [comment]
I believe this is just a documentation error.  Since adding paginated responses to list_servers() the example code in the README doesn't use the correct structure for accessing the data.

**Comment by ens-gijs** [comment]
I'd say it's a documentation error - but Client.list_servers does exist so it seems like more than just documentation and calling `client.client.list_servers()` results in the following error

  File "...pydactyl/api/client.py", line 13, in list_servers
    response = self._api_request(endpoint=endpoint)
  File "...pydactyl/api/base.py", line 106, in _api_request
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://../api/client

**Comment by iamkubi** [comment]
Both exist, they're just part of different API namespaces.  Anything under api/client requires a Client key, and anything under api/application requires an Application key.  A 403 error usually means you're using the wrong type of API key, or a key without sufficient permissions.

**Comment by ens-gijs** [comment]
That make sense, however I don't see how a client key is created LOL. Ptero never has had the most intuitive UI :/

**Comment by iamkubi** [comment]
Agreed, it's not very intuitive.

![image](https://user-images.githubusercontent.com/6176191/143162162-afa152bf-4e74-4868-8faa-3e7274bd4723.png)

**Comment by iamkubi** [comment]
Fixed by 3c45a16
