### ISSUE TITLE
Is it possible?

### ISSUE THREAD

**Issue by GreenDiscord** [iamkubi/pydactyl#38]
Hiya!
I'm trying to make a tkinter application, using this I can control my servers from said app.

The only problem I'm currently facing is getting only all the names from a list, so I can pick which server I would like to edit.

If you know of anyway of doing this please tell me :)

Thank you!

**Comment by iamkubi** [comment]
https://pydactyl.readthedocs.io/en/latest/#pydactyl.api.servers.Servers.list_servers
