### ISSUE TITLE
Can't import PterodactylClient from pydactyl.

### ISSUE THREAD

**Issue by aloyen** [iamkubi/pydactyl#51]
**Describe the bug**
I just write "from pydactyl import PterodactylClient" and got an error.

![изображение](https://user-images.githubusercontent.com/82391289/177039822-3afb5618-d13a-4dd2-ab89-5979afbaba17.png)

**Environment**
 - pydactyl 0.5
 - Python 3.8

**Comment by iamkubi** [comment]
You probably ran `pip install pydactyl` instead of `pip install py-dactyl`
