### ISSUE TITLE
Missing support for /websocket endpoint

### ISSUE THREAD

**Issue by gem7008** [iamkubi/pydactyl#56]
## Description

At the [official Pterodacyl API documentation](https://dashflo.net/docs/api/pterodactyl/v1), under **Client** (`/api/client`) and under **Server** (`/servers/{server}`), there are ~two~ one `GET` endpoint that is not exposed in `pydactyl`.

These endpoints are:
 - **GET** `https://pterodactyl.file.properties/api/client/servers/{server_id}/websocket`
 - ~**GET** https://pterodactyl.file.properties/api/client/servers/{server_id}/resources~

## Benefits

It will grant **two** additional new features:
 - the ability to **get server stats**
 - the ability to **read console logs**

**Comment by iamkubi** [comment]
Resources endpoint isn't missing (https://pydactyl.readthedocs.io/en/latest/clientapi.html#pydactyl.api.client.servers.base.ServersBase.get_server_utilization).

Websocket is.

**Comment by iamkubi** [comment]
Fixed by 1c641ee
