### ISSUE TITLE
/{node}/configuration is missing

### ISSUE THREAD

**Issue by Leymooo** [iamkubi/pydactyl#62]
![image](https://user-images.githubusercontent.com/8667294/192228715-dbe3ccbb-e2df-4d68-a6b6-9a38da07fba1.png)

**Comment by iamkubi** [comment]
Sounds right, I'll get this added.

**Comment by iamkubi** [comment]
Fixed by [c5f25de](https://github.com/iamkubi/pydactyl/commit/c5f25de43dc5e586c020322baa80ea66702b41f0)
