### ISSUE TITLE
You can't use the package anymore after installing

### ISSUE THREAD

**Issue by Joniii11** [iamkubi/pydactyl#69]
**Describe the bug**
I tried to use the package but it just won't work. I tried already pip install `git+https://github.com/iamkubi/pydactyl/` didn't work, `pip install py-dactyl` didn't work. It just won't work. I even see it in the site_packages folder from the python file, but it just won't work.

**To Reproduce**
1. Fails with error: ImportError: cannot import name  'PterodactylClient' from 'pydactyl'

**Expected behavior**
I would have expected to work but it doesn't it doesn't even recognize the package when importing

**Environment**
 - pydactyl version 2.0.0
 - Python version 3.11

**Comment by iamkubi** [comment]
This isn't a problem with pydactyl, you just haven't imported it correctly.

**Comment by Joniii11** [comment]
@iamkubi i imported it like it was shown in the docs!
It did not work!

**Comment by iamkubi** [comment]
Yes, you said it did not work 7 times, so I got that part.  It definitely works though, so this is likely an issue with your local environment.

**Comment by Joniii11** [comment]
And how can i fix it?

**Comment by GattoDev-debug** [comment]
@iamkubi instead of being a dick, you could help sometimes, yknow?

**Comment by GattoDev-debug** [comment]
@Joniii11 ok just found out its py-dactyl instead of pydactyl.

**Comment by Joniii11** [comment]
@GattoDev-debug damn, after 2 years a answer. Well i don't need it anymore i am now a rustacean hehe :D
