### ISSUE TITLE
`create_server` has no external_id argument

### ISSUE THREAD

**Issue by Nzii3** [iamkubi/pydactyl#71]
This should have the `external_id` argument, since Ptero servers allow that. 

Another question, how can I get a server’s UUID/ID when creating a server? Shouldn’t it return an object instead of a status code? This wrapper seems like it needs work.

**Comment by iamkubi** [comment]
https://github.com/iamkubi/pydactyl/pull/67 is open for the external_id, I'll get it merged sooner or later.

It does return an object.

**Comment by Nzii3** [comment]
> #67 is open for the external_id, I'll get it merged sooner or later.
> 
> It does return an object.

I get a response 201 object. But that doesn’t give me information.

**Comment by Nzii3** [comment]
The server is created through.

**Comment by iamkubi** [comment]
Fixed by bfc90d81383c56ae91d527e1c7e4c1e5972eb9e1
