### ISSUE TITLE
create_backup 403 Error

### ISSUE THREAD

**Issue by crocosnipe** [iamkubi/pydactyl#84]
**Describe the bug**
As soon as you execute the function "api.client.servers.backup.create_backup", you get the error 403, although the Application API key has all permissions and other functions with the api, such as api.create_user work

**To Reproduce**
1. Calling the create_backup function with:
 `try:
  response = api.client.servers.backups.create_backup(server_id=5)
  print(response)
except Exception as e:
  print(f"Error: {e}")
`
2. Get the error:
`Error: Forbidden for url: https://panel.bot-hosting.online/api/client/servers/71e5fd98/backups`

**Expected behavior**
I expect a backup to be created in the given server

**Environment**
 - pydactyl version 1.11
 - Python version 3.12

**Additional context**
/

**Comment by iamkubi** [comment]
You can't create backups with application API keys.  It's a client endpoint so you have to use a client key.
