### ISSUE TITLE
Everything else works when i try to make it, but delete user does not work

### ISSUE THREAD

**Issue by Poseidon281** [iamkubi/pydactyl#88]
**Describe the bug**
There is an error when i try to delete a user from my panel

**To Reproduce**
Steps to reproduce the behavior.  Please make sure to include sample code that will reproduce your issue.  If applicable include the full traceback, not just a single line error message.
Code:
```python
    class Modal_Delete_User(discord.ui.Modal):
        def __init__(self, *args, **kwargs) -> None:
            super().__init__(*args, **kwargs)

            self.add_item(discord.ui.InputText(label="User-ID", required=True))

        async def callback(self, interaction: discord.Interaction):
            try:
                user = self.children[0].value
                api.user.delete_user(user_id=user, external_id=None, detail=False)
                embed = discord.Embed(title=f"Result: User with UserID: {user} was Deleted")
                await interaction.response.send_message(embeds=[embed])
                
            except Exception as e:
                embed = discord.Embed(title="Result: A error occured while trying to delete user")
                embed.add_field(name="Error", value=str(e))
                await interaction.response.send_message(embeds=[embed])

``` 

**Expected behavior**

**Environment**
 - pydactyl version [e.g. 0.1.14]
 - Python version [e.g. 3.6] 

**Additional context**

Output:
![Schermafbeelding 2024-04-11 165746](https://github.com/iamkubi/pydactyl/assets/62171904/5d4c93ca-ceaa-46e4-83e3-d4ccbe0d8049)

**Comment by iamkubi** [comment]
I can only assume you're asking me to fix your AI generated code.  Please stop filing issues just because your generated code doesn't work.

**Comment by Poseidon281** [comment]
> I can only assume you're asking me to fix your AI generated code.  Please stop filing issues just because your generated code doesn't work.

This code is not AI generated. It is not even my own code. It is from a buddy of mine who made the bot. I am only making the API into it as a practice. I followed the docs precisely and it does not work. So that is why I made a issue.
