### ISSUE TITLE
power actions only work with admin api key

### ISSUE THREAD

**Issue by vipvenom** [iamkubi/pydactyl#89]
why cant i send power actions with my user's api key , instead i have to use api key of panel admin to do basic stuff like power actions

**Comment by iamkubi** [comment]
you are confused, power actions only work with a client api key.  that's just how the panel works.

**Comment by vipvenom** [comment]
i am sorry the issue is from my part ,look like my host decided to block it using cloudflare for ddos protection ,what a weird way to protect it from ddos
