### ISSUE TITLE
create server on specific node

### ISSUE THREAD

**Issue by vipvenom** [iamkubi/pydactyl#91]
how do i create a server in a specifc node? if i have multiple nodes in a single location? 

create_server(name, user_id, nest_id, egg_id, memory_limit, swap_limit, disk_limit, location_ids=[], port_range=[], environment={}, cpu_limit=0, io_limit=500, database_limit=0, allocation_limit=0, backup_limit=0, docker_image=None, startup_cmd=None, dedicated_ip=False, start_on_completion=True, oom_disabled=True, default_allocation=None, additional_allocations=None, external_id=None, description=None)

cant find anything ehre

**Comment by iamkubi** [comment]
You use the location_ids.
